import { differenceInCalendarDays } from 'date-fns';
import { z } from 'zod';
// Relative import with explicit .js extension: this module is reachable from
// api/ (create_trip), whose Node ESM runtime cannot resolve the @/ alias.
import { ActivityType, type TripData } from '../types/trip.js';

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
export const dateString = z.string().regex(DATE_RE, 'expected YYYY-MM-DD');

const isIanaTimezone = (timezone: string): boolean => {
  try {
    new Intl.DateTimeFormat('en', { timeZone: timezone });
    return true;
  } catch {
    return false;
  }
};

const LAT_MIN = -90;
const LAT_MAX = 90;
const LNG_MIN = -180;
const LNG_MAX = 180;

const coordinatesSchema = z.object({
  lat: z.number().min(LAT_MIN).max(LAT_MAX),
  lng: z.number().min(LNG_MIN).max(LNG_MAX),
});

const activityLocationSchema = z.object({
  lat: z.number().min(LAT_MIN).max(LAT_MAX).optional(),
  lng: z.number().min(LNG_MIN).max(LNG_MAX).optional(),
  address: z.string().optional(),
});

export const activitySchema = z.object({
  activity_id: z.string().default(''), // regenerated by withFreshIds
  activity_name: z.string().min(1),
  activity_type: z.enum(Object.values(ActivityType) as [ActivityType, ...ActivityType[]]).optional(),
  location: activityLocationSchema.optional(),
  duration: z.string().optional(),
  travel_time_from_accommodation: z.string().optional(),
  url: z.string().optional(),
  remarks: z.string().optional(),
  thumbnail_url: z.string().optional(),
  google_place_id: z.string().optional(),
  order: z.number().optional(),
  status: z.object({ done: z.boolean() }).optional(),
});

export const waypointSchema = z.object({
  activity_id: z.string().default(''),
  activity_name: z.string().min(1),
  location: activityLocationSchema.default({}),
  duration: z.string().optional(),
  url: z.string().optional(),
  remarks: z.string().optional(),
  thumbnail_url: z.string().optional(),
  google_place_id: z.string().optional(),
  status: z.object({ done: z.boolean() }).optional(),
});

export const accommodationSchema = z.object({
  name: z.string().min(1),
  address: z.string().default(''),
  check_in: z.string().default(''),
  check_out: z.string().default(''),
  confirmation: z.string().optional(),
  url: z.string().optional(),
  thumbnail_url: z.string().optional(),
  google_place_id: z.string().optional(),
  phone: z.string().optional(),
  room: z.string().optional(),
  host: z.string().optional(),
  location: coordinatesSchema.optional(),
});

// Legacy exports can carry a degenerate {} accommodation; treat nameless as absent
// (mirrors the buildRows name guard).
const optionalAccommodation = z.preprocess(
  (value) => (value && typeof value === 'object' && (value as { name?: unknown }).name ? value : undefined),
  accommodationSchema.optional()
);

const stopSchema = z.object({
  stop_id: z.string().default(''), // regenerated by withFreshIds
  name: z.string().min(1),
  date: z.object({ from: dateString, to: dateString }),
  location: coordinatesSchema,
  duration_days: z.number().optional(),
  travel_time_from_previous: z.string().optional(),
  accommodation: optionalAccommodation,
  activities: z.array(activitySchema).default([]),
  scenic_waypoints: z.array(waypointSchema).default([]),
});

export const wanderlogTripSchema = z.object({
  trip_name: z.string().min(1),
  timezone: z.string().refine(isIanaTimezone, 'must be a valid IANA timezone'),
  stops: z.array(stopSchema).min(1, 'trip must contain at least one stop'),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export type WanderlogTrip = z.infer<typeof wanderlogTripSchema>;

export const toTripData = (parsed: WanderlogTrip): TripData => ({
  ...parsed,
  stops: parsed.stops.map((stop) => ({
    ...stop,
    duration_days:
      stop.duration_days ?? differenceInCalendarDays(new Date(`${stop.date.to}T00:00:00`), new Date(`${stop.date.from}T00:00:00`)),
  })),
});
